[package]
name = "tico"
version = "0.1.0"
edition = "2024"
description = "Yet Another Text Editor"
repository = "https://github.com/plicease/tico"
license = "MIT"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.7", features = ["derive"] }
crossterm = "0.29.0"
dirs = "7.0.0"
regex = "1.13.1"
ropey = "1.6.1"
rustix = { version = "1.1.5", features = ["fs"] }
similar = "3.2.0"
thiserror = "2.0.20"
tree-sitter = "0.26"
tree-sitter-bash = "0.25.1"
tree-sitter-c = "0.24.2"
tree-sitter-cpp = "0.23.4"
tree-sitter-css = "0.25.0"
tree-sitter-fortran = "0.6.0"
tree-sitter-html = "0.23.2"
tree-sitter-json = "0.24.8"
tree-sitter-make = "1.1.1"
tree-sitter-md = "0.5.3"
tree-sitter-perl = "1.1.2"
tree-sitter-python = "0.25.0"
tree-sitter-rust = "0.24.2"
tree-sitter-sequel = "0.3.11"
tree-sitter-toml = "0.20.0"
tree-sitter-yaml = "0.7.2"
unicode-segmentation = "1.13.3"
unicode-width = "0.2.2"


[package.metadata.deb]
maintainer = "Nobody <devnull@wdlabs.com>"
copyright = "Nobody"
extended-description = """\
Yet Another Text Editor"""
section = "utils"
priority = "optional"
assets = [
    ["target/release/tico", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/tico/README.md", "644"],
    ["LICENSE", "usr/share/doc/tico/LICENSE", "644"],
]

